### ISSUE TITLE
how to compile it

### ISSUE THREAD

**Issue by mistepien** [hank/dsf2flac#1]
How to compile under linux?

**Comment by mishan** [comment]
@mistepien Well, short of using the IDE the author is using, you'd have to compile it by hand, making sure to get all the CFLAGS (compilation time) and LDFLAGS (link time) correct.

I just discovered this project last night and saw your issue. I was going to just toss in some basic Makefiles but that's not as portable -- different systems have libraries installed in different places. I'm adding an autoconf/automake system to dsf2flac so that you can simply do `./configure && make && make install` once I'm done. I'm at least 80% of the way finished. It's been over 10 years since I've mucked around with writing my own autotools stuff.

**Comment by mistepien** [comment]
On 22/04/16 05:47, Misha Nasledov wrote:

> @mistepien Well, short of using the IDE the author is using, you'd have to compile it by hand, making sure to get all the CFLAGS (compilation time) and LDFLAGS (link time) correct.
> 
> I just discovered this project last night and saw your issue. I was going to just toss in some basic Makefiles but that's not as portable -- different systems have libraries installed in different places. I'm adding an autoconf/automake system to dsf2flac so that you can simply do `./configure && make && make install` once I'm done. I'm at least 80% of the way finished. It's been over 10 years since I've mucked around with writing my own autotools stuff.
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/hank/dsf2flac/issues/1#issuecomment-213233132
> 
> Great news. Thanks a lot!
> I appreciate your efforts. This will make dsf2flac more portable.

michal

**Comment by mishan** [comment]
@mistepien You should be able to compile it on Linux no problemo now. Changes have been merged into master. And @hank says he's working on getting it to build under Cygwin as well, which is pretty cool!

Best,
Misha

**Comment by hank** [comment]
Just tried in linux with gcc4 and gcc6 - both work now.  Just do ./autogen.sh, ./configure, make and it will build.
