### ISSUE TITLE
Incompatible sample rate combination

### ISSUE THREAD

**Issue by JimZipCode** [hank/dsf2flac#21]
I just installed on Ubuntu 19.10.  First, thanks for the autogen.sh!  There were a ton of dependencies I had to pull with apt-get install; but ultimately autogen + make + sudo make install worked a treat.  Brilliant.

So I try to convert a file, and I get this error:

> $ dsf2flac -i 01_Smoke-Mirrors_Yarlung-Records_YAR87598DSD_2ch256.dsf
> dsf2flac 0.1Rev54
> 
> Input file
> 	01_Smoke-Mirrors_Yarlung-Records_YAR87598DSD_2ch256.dsf
> Output format
> 	SampleRate: 88200Hz
> 	Depth: 24bit
> 	Dither: true
> 	Scale: 4.0dB
> Sorry, incompatible sample rate combination

What's it mean?  How do I fix?

**Comment by pms967** [comment]
While waiting for an authoritative answer from a developer, a couple of hypothesis: 

* Maybe your file have a sample rate which is a multiple of 48K rather than 44.1K, in which case perhaps you must choose an output sample rate which is also a multiple of 48K (such as 96K);

* Judging from the file name, your file looks to be DSD 256x (rather than "standard" 64x). May be dsd2flac is unable to handle it, or possibly you have to use an higher output sample rate.

Or may be even a combination of both things. Try again with different options, and report here the results...

**Comment by jackocleebrown** [comment]
Hi, apologies for the extreme delay. Better late than never I hope.

dsf2flac can do conversion at sample rate ratios of 8, 16 or 32. Your source file is, by the look of it, DSD 256x and your output rate is 88200. This is a ratio of 256*44100/88200 = 128. The easiest fix is to change the output sample rate to 352.8 kHz and this would give a ratio of 256*44100/88200 = 32, which should work.

As a note, the code can be updated for other ratios pretty easily by adding new filters to filters.cpp and adjusting the code that selects the filter in dsd_decimator.cpp
